import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createRecord,isDraft,readHistory,writeHistory,upsert,findHistory,mergeHistory,HISTORY_KEY,LEGACY_KEY} from '../public/history.js';
const fields=JSON.parse(readFileSync(new URL('../public/defaults.json',import.meta.url)));const keys=Object.keys(fields);const draft=()=>({version:1,fields:{...fields},review:[],transcript:'private transcript',notes:'private notes'});
function storage(){const map=new Map();return {getItem:key=>map.get(key)??null,setItem:(key,value)=>map.set(key,value)};}
test('legacy migration preserves fields without duplicating history',()=>{const s=storage();s.setItem(LEGACY_KEY,JSON.stringify(draft()));const first=readHistory(s,keys);assert.equal(first.items.length,1);assert.equal(first.items[0].fields.company,fields.company);writeHistory(s,first.items);const second=readHistory(s,keys);assert.equal(second.migrated,false);assert.equal(second.items.length,1);assert.ok(s.getItem(LEGACY_KEY));});
test('updating one proposal leaves earlier proposals intact',()=>{const a=createRecord(draft(),{id:'a',now:'2026-09-19T01:00:00Z'}),b=createRecord(draft(),{id:'b',now:'2026-09-19T02:00:00Z'});const rows=upsert([a,b],{...b,fields:{...b.fields,company:'New name'}});assert.equal(rows[0].fields.company,fields.company);assert.equal(rows.length,2);assert.equal(rows[1].fields.company,'New name');});
test('transcripts and operator instructions do not enter persisted history',()=>{const r=createRecord(draft(),{id:'test'});assert.equal(r.transcript,undefined);assert.equal(r.notes,undefined);assert.ok(!JSON.stringify(r).includes('private transcript'));});
test('history search, review filtering and recency order work together',()=>{const a=createRecord(draft(),{id:'a',now:'2026-09-19T01:00:00Z'}),b={...createRecord(draft(),{id:'b',now:'2026-09-19T02:00:00Z'}),reviewed:true};b.fields.company='Blue Dot';assert.equal(findHistory([a,b])[0].id,'b');assert.equal(findHistory([a,b],'blue','ready').length,1);assert.equal(findHistory([a,b],'blue','review').length,0);});
test('invalid history and incomplete imports cannot silently replace saved records',()=>{assert.equal(isDraft({version:1,fields:{company:'Partial'},review:[]},keys),false);const s=storage();s.setItem(HISTORY_KEY,'broken');assert.throws(()=>readHistory(s,keys));assert.equal(s.getItem(HISTORY_KEY),'broken');});
test('storage failure is surfaced rather than evicting older proposals',()=>{const s={setItem(){throw Error('Quota exceeded');}};assert.throws(()=>writeHistory(s,[createRecord(draft(),{id:'a'})]),/Quota exceeded/);});

test('saves from another tab keep new records and newer edits',()=>{const a=createRecord(draft(),{id:'a',now:'2026-09-19T01:00:00Z'}),b=createRecord(draft(),{id:'b',now:'2026-09-19T02:00:00Z'});const newer={...a,fields:{...a.fields,company:'Edited elsewhere'},updatedAt:'2026-09-19T03:00:00Z'};const merged=mergeHistory([newer,b],[a]);assert.equal(merged.length,2);assert.equal(merged.find(x=>x.id==='a').fields.company,'Edited elsewhere');});
